language:
  - php

php:
  - 5.3

branches:
  only:
    - master
    - develop

before_script:
  - pear channel-discover pear.phing.info
  - pear channel-discover pear.cakephp.org
  - pear install phing/phing
  - pear install PHP_CodeSniffer-1.5.6
  - pear install cakephp/CakePHP_CodeSniffer-0.1.30
  - phpenv rehash

script:
  - phing build
