language:
  - php

php:
  - 5.3

branches:
  only:
    - master
    - develop

before_script:
  - pear channel-discover pear.phing.info
  - pear channel-discover pear.cakephp.org
  - pear install phing/phing PHP_CodeSniffer cakephp/CakePHP_CodeSniffer
  - phpenv rehash

script:
  - phing build